name = "spino-gambinospiel-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spino-gambinospiel.de"
HMAC_KEY = "ad34fba330239ff58350afeb6f33fc6fd2b3506d4eb55f74001f31c4b737568e"
COOKIE_NAME = "bw9"
PLAY_PATH = "explore"
BUTTON_ID = "p572cbaca1ce5c41f2933d836eb33b3f2"
GATE_SALT = "f64a1c54b7ef6b3c"
