name = "spino-gambinospiel-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spino-gambinospiel.de"
HMAC_KEY = "ad34fba330239ff58350afeb6f33fc6fd2b3506d4eb55f74001f31c4b737568e"
COOKIE_NAME = "wz9"
PLAY_PATH = "launch"
BUTTON_ID = "p572cbaca1ce5c41f2933d836eb33b3f2"
GATE_SALT = "a3e9ba00c571e777"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "rysw"
CTA_SELECTOR = ".play-button"
